# This code was AUTOGENERATED.
# Change it to fit your test case.
class Solution:
    def calculate(self, s: str) -> int:
        result = 0
        number = 0
        sign = 1
        stk = []
        for c in s:
            if c in {"+", "-"}:
                result = result + (number * sign)
                sign = 1 if c == "+" else -1
                number = 0
            elif c.isdigit():
                number = int(c) + number * 10
            elif c == "(":
                stk.append(result)
                stk.append(sign)
                result = 0
                sign = 1
            elif c == ")":
                result += number * sign
                pushed_sign = stk.pop(-1)
                pushed_res = stk.pop(-1)
                result = result * pushed_sign
                result += pushed_res
                number = 0

        return result + number * sign

