# This code was AUTOGENERATED.
import unittest
from lc2000_reverse_prefix_of_word import Solution

class TestSolution(unittest.TestCase):
    def test_reversePrefix(self):
        s = Solution()
        self.assertEqual(s.reversePrefix("abcdefd", 'd'), "dcbaefd")
        self.assertEqual(s.reversePrefix("xyxzxe", 'z'), "zxyxxe")
        self.assertEqual(s.reversePrefix("abcd", 'z'), "abcd")

if __name__ == "__main__":
    unittest.main()
