# This code was AUTOGENERATED.
import unittest
from lc165_compare_version_numbers import Solution

class TestSolution(unittest.TestCase):
    def test_compareVersion(self):
        s = Solution()
        self.assertEqual(s.compareVersion("1.01", "1.001"), 0)
        self.assertEqual(s.compareVersion("1.0", "1.0.0"), 0)
        self.assertEqual(s.compareVersion("0.1", "1.1"), -1)

if __name__ == "__main__":
    unittest.main()
