# This code was AUTOGENERATED.
# Change it to fit your test case.
import implement_trie_prefix_tree
import pytest

# This test will run once per test case
def test_problem():
    obj = implement_trie_prefix_tree.Trie()
    obj.insert("apple")
    obj.insert("applepie")
    obj.insert("banana")
    obj.insert("app")
    assert obj.search("apple") == True 
    assert obj.search("cherry") == False
    assert obj.search("banana") == True 
    assert obj.search("application") == False 
    assert obj.startsWith("appl") == True 



