# This code was AUTOGENERATED.
# Change it to fit your test case.
import lc200_number_of_islands
import pytest

@pytest.mark.parametrize(
    ("grid", "output"),
    [
        ([
          ["1","1","1","1","0"],
          ["1","1","0","1","0"],
          ["1","1","0","0","0"],
          ["0","0","0","0","0"]
         ], 1
        ),
        ([
          ["1","0","1","0","0"]
         ], 2
        ),
    ]
)

# This test will run once per test case
def test_problem(grid, output):
    s = lc200_number_of_islands.Solution()
    assert output == s.numIslands(grid)
