# This code was AUTOGENERATED.
# Change it to fit your test case.
import lc155
import pytest

@pytest.mark.parametrize(
    ("operations", "entries", "output"),
    [
        (["MinStack","push","push","push","getMin","pop","top","getMin"], 
         [[],[-2],[0],[-3],[],[],[],[]], 
         [None,None,None,None,-3,None,0,-2]),
    ]
)

def test_problem(operations, entries, output):
    stk = None
    cal_output = []
    for index, operation in enumerate(operations):
        match operation:
            case "MinStack":
                stk = lc155.MinStack()
                cal_output.append(None)
            case "push":
                stk.push(entries[index][0])
                cal_output.append(None)
            case "pop":
                pop_ = stk.pop()
                cal_output.append(pop_)
            case "top":
                top_ = stk.top()
                cal_output.append(top_)
            case "getMin":
                min_ = stk.getMin()
                cal_output.append(min_)
    assert cal_output == output
