# This code was AUTOGENERATED.
# Change it to fit your test case.
import lc104_maximum_depth_of_binary_tree
import pytest
from lib.binary_tree import TreeNode


head = TreeNode()
level_1_1 = TreeNode()
level_1_2 = TreeNode()
level_2_1 = TreeNode()
head.left = level_1_1
head.right = level_1_2
level_1_1.left = level_2_1

@pytest.mark.parametrize(
    ("head", "depth"),
    [
        (head, 3),
    ]
)

def test_problem(head, depth):
    s = lc104_maximum_depth_of_binary_tree.Solution()
    assert s.calDepth(head) == depth
    # assert calculated_res == output
