# This code was AUTOGENERATED.
# Change it to fit your test case.
import lc300_longest_increasing_subsequence
import pytest

@pytest.mark.parametrize(
    ("input_1", "input_2", "output"),
    [
        # parametrized test case 1
        ([1, 3, 4, 8, 7, 9, 3, 5, 1], 2, [[1, 1, 3], [3, 4, 5], [7, 8, 9]]),
        # parametrized test case 2
        ([1,3,3,2,7,3], 2, []),
    ]
)

# This test will run once per test case
def test_problem(input_1, input_2, output):
    s = lc300_longest_increasing_subsequence.Solution()
    # Call your program here. For example:
    # calculated_res = s.fn_name(input_1, input_2)
    # assert calculated_res == output
