# This code was AUTOGENERATED.
# Change it to fit your test case.
import lc130_surrounded_regions
import pytest

@pytest.mark.parametrize(
    ("board", "output"),
    [
        ([["X","X","X","X"],["X","O","O","X"],["X","X","O","X"],["X","O","X","X"]], 
         [["X","X","X","X"],["X","X","X","X"],["X","X","X","X"],["X","O","X","X"]]),
    ]
)

# This test will run once per test case
def test_problem(board, output):
    s = lc130_surrounded_regions.Solution()
    s.solve(board)
    assert board == output
