# This code was AUTOGENERATED.
# Change it to fit your test case.
import lc19_remove_nth_node_from_end_of_list
import pytest

@pytest.mark.parametrize(
    ("head", "n", "new_head"),
    [
        (),
    ]
)

def test_problem(input_1, input_2, output):
    s = lc19_remove_nth_node_from_end_of_list.Solution()
